/**
 * ЗАДАЧА 5 — тестовая спецификация щита на 48 модулей:
 * вводной автомат, УЗИП, реле напряжения, УЗО, групповые автоматы, резерв.
 */

import type { SpecItem } from "./types";

export const TEST_SPEC_48: SpecItem[] = [
  {
    id: "t1",
    tag: "QF1",
    role: "input",
    deviceType: "breaker",
    manufacturer: "IEK",
    series: "ВА47",
    poles: 3,
    ratedCurrent: 63,
    qty: 1,
    phase: "L1,L2,L3",
    load: "Ввод 380В",
  },
  {
    id: "t2",
    tag: "FV1",
    role: "spd",
    deviceType: "spd",
    manufacturer: "IEK",
    poles: 3,
    qty: 1,
    phase: "L1,L2,L3",
    load: "Защита от импульсных перенапряжений",
  },
  {
    id: "t3",
    tag: "KV1",
    role: "voltage-relay",
    deviceType: "voltage_relay",
    manufacturer: "IEK",
    ratedCurrent: 63,
    qty: 1,
    phase: "L1,L2,L3",
    load: "Контроль напряжения",
  },
  {
    id: "t4",
    tag: "QD1",
    role: "rcd",
    deviceType: "rcd",
    manufacturer: "IEK",
    series: "ВД1-63",
    poles: 4,
    ratedCurrent: 63,
    qty: 1,
    phase: "L1,L2,L3",
    load: "Общее УЗО 300мА",
  },
  {
    id: "t5",
    tag: "QD2",
    role: "rcd",
    deviceType: "rcd",
    manufacturer: "IEK",
    series: "ВД1-63",
    poles: 2,
    ratedCurrent: 25,
    qty: 2,
    phase: "L1",
    load: "УЗО розеточных групп 30мА",
  },
  {
    id: "t6",
    tag: "QF2",
    role: "group",
    deviceType: "breaker",
    manufacturer: "IEK",
    series: "ВА47",
    poles: 1,
    ratedCurrent: 16,
    qty: 6,
    phase: "L1",
    load: "Освещение",
  },
  {
    id: "t7",
    tag: "QF3",
    role: "group",
    deviceType: "breaker",
    manufacturer: "IEK",
    series: "ВА47",
    poles: 1,
    ratedCurrent: 25,
    qty: 6,
    phase: "L2",
    load: "Розетки",
  },
  {
    id: "t8",
    tag: "QF4",
    role: "group",
    deviceType: "breaker",
    manufacturer: "IEK",
    series: "ВА47",
    poles: 3,
    ratedCurrent: 32,
    qty: 1,
    phase: "L1,L2,L3",
    load: "Зарядная станция EV",
  },
];
