/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactCardRouteImport } from './routes/contact-card'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RabotyIndexRouteImport } from './routes/raboty.index'
import { Route as SmetaTokenRouteImport } from './routes/smeta.$token'
import { Route as RabotySlugRouteImport } from './routes/raboty.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicTelegramHealthRouteImport } from './routes/api/public/telegram-health'
import { Route as ApiPublicSupabaseKeepaliveRouteImport } from './routes/api/public/supabase-keepalive'
import { Route as ApiPublicContactCardDotpdfRouteImport } from './routes/api/public/contact-card[.]pdf'
import { Route as AuthenticatedEstimateIdRouteImport } from './routes/_authenticated/estimate.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactCardRoute = ContactCardRouteImport.update({
  id: '/contact-card',
  path: '/contact-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RabotyIndexRoute = RabotyIndexRouteImport.update({
  id: '/raboty/',
  path: '/raboty/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmetaTokenRoute = SmetaTokenRouteImport.update({
  id: '/smeta/$token',
  path: '/smeta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RabotySlugRoute = RabotySlugRouteImport.update({
  id: '/raboty/$slug',
  path: '/raboty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramHealthRoute = ApiPublicTelegramHealthRouteImport.update({
  id: '/api/public/telegram-health',
  path: '/api/public/telegram-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupabaseKeepaliveRoute =
  ApiPublicSupabaseKeepaliveRouteImport.update({
    id: '/api/public/supabase-keepalive',
    path: '/api/public/supabase-keepalive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactCardDotpdfRoute =
  ApiPublicContactCardDotpdfRouteImport.update({
    id: '/api/public/contact-card.pdf',
    path: '/api/public/contact-card.pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEstimateIdRoute = AuthenticatedEstimateIdRouteImport.update({
  id: '/estimate/$id',
  path: '/estimate/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/contact-card': typeof ContactCardRoute
  '/mcp': typeof McpRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/raboty/$slug': typeof RabotySlugRoute
  '/smeta/$token': typeof SmetaTokenRoute
  '/raboty/': typeof RabotyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/estimate/$id': typeof AuthenticatedEstimateIdRoute
  '/api/public/contact-card.pdf': typeof ApiPublicContactCardDotpdfRoute
  '/api/public/supabase-keepalive': typeof ApiPublicSupabaseKeepaliveRoute
  '/api/public/telegram-health': typeof ApiPublicTelegramHealthRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/contact-card': typeof ContactCardRoute
  '/mcp': typeof McpRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/raboty/$slug': typeof RabotySlugRoute
  '/smeta/$token': typeof SmetaTokenRoute
  '/raboty': typeof RabotyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/estimate/$id': typeof AuthenticatedEstimateIdRoute
  '/api/public/contact-card.pdf': typeof ApiPublicContactCardDotpdfRoute
  '/api/public/supabase-keepalive': typeof ApiPublicSupabaseKeepaliveRoute
  '/api/public/telegram-health': typeof ApiPublicTelegramHealthRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/contact-card': typeof ContactCardRoute
  '/mcp': typeof McpRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/raboty/$slug': typeof RabotySlugRoute
  '/smeta/$token': typeof SmetaTokenRoute
  '/raboty/': typeof RabotyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/estimate/$id': typeof AuthenticatedEstimateIdRoute
  '/api/public/contact-card.pdf': typeof ApiPublicContactCardDotpdfRoute
  '/api/public/supabase-keepalive': typeof ApiPublicSupabaseKeepaliveRoute
  '/api/public/telegram-health': typeof ApiPublicTelegramHealthRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/contact-card'
    | '/mcp'
    | '/prices'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/raboty/$slug'
    | '/smeta/$token'
    | '/raboty/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/estimate/$id'
    | '/api/public/contact-card.pdf'
    | '/api/public/supabase-keepalive'
    | '/api/public/telegram-health'
    | '/api/public/photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/contact-card'
    | '/mcp'
    | '/prices'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/raboty/$slug'
    | '/smeta/$token'
    | '/raboty'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/estimate/$id'
    | '/api/public/contact-card.pdf'
    | '/api/public/supabase-keepalive'
    | '/api/public/telegram-health'
    | '/api/public/photo/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/contact-card'
    | '/mcp'
    | '/prices'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/raboty/$slug'
    | '/smeta/$token'
    | '/raboty/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/estimate/$id'
    | '/api/public/contact-card.pdf'
    | '/api/public/supabase-keepalive'
    | '/api/public/telegram-health'
    | '/api/public/photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  ContactCardRoute: typeof ContactCardRoute
  McpRoute: typeof McpRoute
  PricesRoute: typeof PricesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  RabotySlugRoute: typeof RabotySlugRoute
  SmetaTokenRoute: typeof SmetaTokenRoute
  RabotyIndexRoute: typeof RabotyIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicContactCardDotpdfRoute: typeof ApiPublicContactCardDotpdfRoute
  ApiPublicSupabaseKeepaliveRoute: typeof ApiPublicSupabaseKeepaliveRoute
  ApiPublicTelegramHealthRoute: typeof ApiPublicTelegramHealthRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-card': {
      id: '/contact-card'
      path: '/contact-card'
      fullPath: '/contact-card'
      preLoaderRoute: typeof ContactCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raboty/': {
      id: '/raboty/'
      path: '/raboty'
      fullPath: '/raboty/'
      preLoaderRoute: typeof RabotyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smeta/$token': {
      id: '/smeta/$token'
      path: '/smeta/$token'
      fullPath: '/smeta/$token'
      preLoaderRoute: typeof SmetaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raboty/$slug': {
      id: '/raboty/$slug'
      path: '/raboty/$slug'
      fullPath: '/raboty/$slug'
      preLoaderRoute: typeof RabotySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-health': {
      id: '/api/public/telegram-health'
      path: '/api/public/telegram-health'
      fullPath: '/api/public/telegram-health'
      preLoaderRoute: typeof ApiPublicTelegramHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/supabase-keepalive': {
      id: '/api/public/supabase-keepalive'
      path: '/api/public/supabase-keepalive'
      fullPath: '/api/public/supabase-keepalive'
      preLoaderRoute: typeof ApiPublicSupabaseKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-card.pdf': {
      id: '/api/public/contact-card.pdf'
      path: '/api/public/contact-card.pdf'
      fullPath: '/api/public/contact-card.pdf'
      preLoaderRoute: typeof ApiPublicContactCardDotpdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estimate/$id': {
      id: '/_authenticated/estimate/$id'
      path: '/estimate/$id'
      fullPath: '/estimate/$id'
      preLoaderRoute: typeof AuthenticatedEstimateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEstimateIdRoute: typeof AuthenticatedEstimateIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEstimateIdRoute: AuthenticatedEstimateIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  ContactCardRoute: ContactCardRoute,
  McpRoute: McpRoute,
  PricesRoute: PricesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  RabotySlugRoute: RabotySlugRoute,
  SmetaTokenRoute: SmetaTokenRoute,
  RabotyIndexRoute: RabotyIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicContactCardDotpdfRoute: ApiPublicContactCardDotpdfRoute,
  ApiPublicSupabaseKeepaliveRoute: ApiPublicSupabaseKeepaliveRoute,
  ApiPublicTelegramHealthRoute: ApiPublicTelegramHealthRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
